[package]
name = "orml-xtokens"
description = "Cross-chain token transfer."
repository = "https://github.com/open-web3-stack/open-runtime-module-library/tree/master/xtokens"
license = "Apache-2.0"
version = "0.4.1-dev"
authors = ["Acala Developers"]
edition = "2021"

[dependencies]
codec = { package = "parity-scale-codec", version = "3.0.0", default-features = false }
scale-info = { version = "2.1.2", default-features = false, features = ["derive"] }
serde = { version = "1.0.136", optional = true }
log = { version = "0.4.14", default-features = false }

# substrate
frame-support = { git = "https://github.com/peaqnetwork/substrate", default-features = false , branch = "peaq-polkadot-v0.9.38" }
frame-system = { git = "https://github.com/peaqnetwork/substrate", default-features = false , branch = "peaq-polkadot-v0.9.38" }
sp-io = { git = "https://github.com/peaqnetwork/substrate", default-features = false , branch = "peaq-polkadot-v0.9.38" }
sp-runtime = { git = "https://github.com/peaqnetwork/substrate", default-features = false , branch = "peaq-polkadot-v0.9.38" }
sp-std = { git = "https://github.com/peaqnetwork/substrate", default-features = false , branch = "peaq-polkadot-v0.9.38" }

# cumulus
cumulus-primitives-core = { git = "https://github.com/peaqnetwork/cumulus", default-features = false , branch = "peaq-polkadot-v0.9.38" }

# polkadot
pallet-xcm = { git = "https://github.com/peaqnetwork/polkadot", default-features = false , branch = "peaq-polkadot-v0.9.38" }
xcm = { git = "https://github.com/peaqnetwork/polkadot", default-features = false , branch = "peaq-polkadot-v0.9.38" }
xcm-executor = { git = "https://github.com/peaqnetwork/polkadot", default-features = false , branch = "peaq-polkadot-v0.9.38" }

# orml
orml-traits = { path = "../traits", default-features = false}
orml-xcm-support = { path = "../xcm-support", default-features = false }

[dev-dependencies]
# substrate
pallet-balances = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.38" }
sp-core = { git = "https://github.com/peaqnetwork/substrate", branch = "peaq-polkadot-v0.9.38" }

# cumulus
cumulus-pallet-dmp-queue = { git = "https://github.com/peaqnetwork/cumulus", branch = "peaq-polkadot-v0.9.38" }
cumulus-pallet-xcm = { git = "https://github.com/peaqnetwork/cumulus", branch = "peaq-polkadot-v0.9.38" }
cumulus-pallet-xcmp-queue = { git = "https://github.com/peaqnetwork/cumulus", branch = "peaq-polkadot-v0.9.38" }
cumulus-primitives-core = { git = "https://github.com/peaqnetwork/cumulus", branch = "peaq-polkadot-v0.9.38" }
parachain-info = { git = "https://github.com/peaqnetwork/cumulus", branch = "peaq-polkadot-v0.9.38" }

# polkadot
polkadot-parachain = { git = "https://github.com/peaqnetwork/polkadot", branch = "peaq-polkadot-v0.9.38" }
polkadot-runtime-parachains = { git = "https://github.com/peaqnetwork/polkadot", branch = "peaq-polkadot-v0.9.38" }
xcm-builder = { git = "https://github.com/peaqnetwork/polkadot", branch = "peaq-polkadot-v0.9.38" }
xcm-simulator = { git = "https://github.com/peaqnetwork/polkadot", branch = "peaq-polkadot-v0.9.38" }

# orml
orml-tokens = { path = "../tokens" }
orml-xcm = { path = "../xcm" }

[features]
default = ["std"]
std = [
	"serde",

	"codec/std",
	"cumulus-primitives-core/std",
	"frame-support/std",
	"frame-system/std",
	"orml-traits/std",
	"orml-xcm-support/std",
	"pallet-xcm/std",
	"scale-info/std",
	"sp-io/std",
	"sp-runtime/std",
	"sp-std/std",
	"xcm-executor/std",
	"xcm/std",
	"log/std",
]
runtime-benchmarks = [
	"frame-support/runtime-benchmarks",
	"frame-system/runtime-benchmarks",
	"pallet-xcm/runtime-benchmarks",
	"sp-runtime/runtime-benchmarks",
	"xcm-builder/runtime-benchmarks",
	"xcm-executor/runtime-benchmarks",
]
try-runtime = [
	"frame-support/try-runtime",
	"frame-system/try-runtime",
	"pallet-xcm/try-runtime",
]
